[package]
name = "projections"
version = "0.1.0"
authors = ["jb <wozgonon@gmail.com>"]

[lib]
name = "libwebmap"
path = "src/lib.rs"

[[bin]]
name = "webmap"
path = "bin/webmap.rs"

[dependencies]
serde_json = "1.0.17"
serde = "1.0.54"
